name: Update Default Policy

on:
  schedule:
    # Run every week
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  update-default-policy:
    runs-on: ubuntu-latest
    name: Update Default Policy
    if: ${{ secrets.GH_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10.6"
        - run: |
            sudo apt update
            sudo apt install gh
            pip3 install --upgrade pip
            pip3 install -r scripts/requirements.txt
            python3 scripts/update-policy.py
            python3 scripts/create-pr.py
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}